#!/usr/bin/env python3
"""Create a GitHub issue for SDK skill-efficacy gaps.

This script parses skill-efficacy evaluation results, maps failing tests to sdk-* rules,
and opens a tracking issue with `gh issue create`. Use `--dry-run` to print the
issue content without creating the issue.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import statistics
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

TEST_TO_RULE_MAP = {
    "TestLatestSdk": "sdk-dotnet-cosmos-package-id",
    "TestSingletonClient": "sdk-singleton-client",
    "TestPreferredRegions": "sdk-preferred-regions",
    "TestDirectModeDotnet": "sdk-connection-mode",
    "TestDirectModeJava": "sdk-connection-mode",
    "TestRetry": "sdk-retry-429",
    "TestDiagnostics": "sdk-diagnostics",
    "TestLifecycle": "sdk-singleton-client",
    "TestEndToEndTimeout": "sdk-async-api",
    "TestNoBlockingInAsync": "sdk-async-api",
    "TestCacheMetadata": "sdk-singleton-client",
    "TestPythonAsyncClient": "sdk-python-async-deps",
}

PREFERRED_RULES_DIR = Path("skills/cosmosdb-best-practices/rules")
FALLBACK_RULES_DIR = Path("skills/cosmosdb-best-practices/rules")
URL_KEYS = (
    "analysis_url",
    "analysisUrl",
    "run_analysis_url",
    "runAnalysisUrl",
    "run_url",
    "runUrl",
    "html_url",
    "htmlUrl",
    "workflow_run_url",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a GitHub issue for SDK skill-efficacy rule gaps"
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--results-file",
        help="Path to results.json generated by scripts/msbench-eval.py",
    )
    source.add_argument(
        "--failing-tests",
        help="JSON string describing failing test names or result payload",
    )
    parser.add_argument(
        "--repo",
        default="AzureCosmosDB/cosmosdb-agent-kit",
        help="GitHub repository in OWNER/REPO format",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the issue title and body without creating an issue",
    )
    return parser.parse_args()


def load_input(args: argparse.Namespace) -> Any:
    if args.results_file:
        with open(args.results_file, "r", encoding="utf-8") as handle:
            return json.load(handle)
    return json.loads(args.failing_tests)


def detect_rules_dir() -> Path:
    repo_root = Path(__file__).resolve().parents[1]
    preferred = repo_root / PREFERRED_RULES_DIR
    fallback = repo_root / FALLBACK_RULES_DIR
    if preferred.exists():
        return PREFERRED_RULES_DIR
    if fallback.exists():
        return FALLBACK_RULES_DIR
    return PREFERRED_RULES_DIR


def format_percent(value: float | int | None) -> str:
    if value is None:
        return "n/a"
    value = round(float(value), 1)
    if value.is_integer():
        return str(int(value))
    return f"{value:.1f}"


def coerce_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def normalize_percent_rate(value: Any) -> float | None:
    if not isinstance(value, (int, float)):
        return None
    rate = float(value)
    if 0 <= rate <= 1:
        return rate * 100
    return rate


def coerce_nonnegative_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return max(0, value)
    if isinstance(value, float) and value.is_integer():
        return max(0, int(value))
    return None


def extract_numeric_pass_rate(payload: Any) -> float | None:
    if isinstance(payload, dict):
        aggregate = payload.get("aggregate")
        if isinstance(aggregate, dict):
            pass_rate = aggregate.get("pass_rate")
            if isinstance(pass_rate, dict):
                normalized = normalize_percent_rate(pass_rate.get("mean"))
                if normalized is not None:
                    return normalized
        summary = payload.get("summary")
        if isinstance(summary, dict):
            normalized = normalize_percent_rate(summary.get("pass_rate"))
            if normalized is not None:
                return normalized
        for key in ("pass_rate", "average_pass_rate", "avg_pass_rate"):
            normalized = normalize_percent_rate(payload.get(key))
            if normalized is not None:
                return normalized
    return None


def find_analysis_url(payload: Any) -> str:
    queue = [payload]
    seen_ids: set[int] = set()
    while queue:
        current = queue.pop(0)
        current_id = id(current)
        if current_id in seen_ids:
            continue
        seen_ids.add(current_id)
        if isinstance(current, dict):
            for key in URL_KEYS:
                value = current.get(key)
                if isinstance(value, str) and value.strip():
                    return value.strip()
            queue.extend(current.values())
        elif isinstance(current, list):
            queue.extend(current)

    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repository = os.environ.get("GITHUB_REPOSITORY")
    run_id = os.environ.get("GITHUB_RUN_ID")
    if repository and run_id:
        return f"{server}/{repository}/actions/runs/{run_id}"
    return "Analysis URL not available"


def mapped_test_name(test_name: str) -> str | None:
    if test_name in TEST_TO_RULE_MAP:
        return test_name
    matches = re.findall(r"Test[A-Za-z0-9_]+", test_name)
    for match in matches:
        if match in TEST_TO_RULE_MAP:
            return match
    for candidate in TEST_TO_RULE_MAP:
        if candidate in test_name:
            return candidate
    return None


def test_to_rule(test_name: str) -> str | None:
    canonical_name = mapped_test_name(test_name)
    if canonical_name is None:
        return None
    return TEST_TO_RULE_MAP[canonical_name]


def extract_test_name(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        for key in ("name", "test", "test_name", "classname", "nodeid", "id"):
            value = item.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return str(item)


def is_failure(item: Any) -> bool:
    if isinstance(item, str):
        return True
    if not isinstance(item, dict):
        return False
    outcome = str(item.get("outcome") or item.get("status") or item.get("result") or "").lower()
    if outcome in {"failed", "failure", "error", "errors", "fail"}:
        return True
    for key in ("failed", "is_failed", "failure"):
        value = item.get(key)
        if isinstance(value, bool):
            return value
    return False


def extract_tests_from_mapping(mapping: dict[str, Any]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []

    consistency = mapping.get("test_consistency")
    if isinstance(consistency, dict):
        for name, stats in consistency.items():
            if not isinstance(stats, dict):
                continue
            fail_count = coerce_nonnegative_int(stats.get("fail_count")) or 0
            observed_count = coerce_nonnegative_int(stats.get("total_runs")) or 1
            records.append(
                {
                    "name": name,
                    "failed": fail_count > 0,
                    "fail_count": fail_count,
                    "observed_count": observed_count,
                    "pass_rate": normalize_percent_rate(stats.get("pass_rate")),
                    "stability": stats.get("stability"),
                }
            )
        return records

    source_total_runs = coerce_nonnegative_int(mapping.get("total_runs"))
    source_failed_runs = coerce_nonnegative_int(mapping.get("failed_runs"))

    for key in ("tests", "test_results", "failing_tests", "failed_tests", "failures"):
        values = mapping.get(key)
        if values is None:
            continue
        if isinstance(values, dict):
            iterable = [
                {"name": name, **details} if isinstance(details, dict) else {"name": name, "outcome": details}
                for name, details in values.items()
            ]
        else:
            iterable = coerce_list(values)

        for item in iterable:
            name = extract_test_name(item)
            failed = key in {"failing_tests", "failed_tests", "failures"} or is_failure(item)
            observed_count = source_total_runs or 1
            fail_count = (
                source_failed_runs if failed and source_failed_runs is not None else (1 if failed else 0)
            )
            record = {"name": name, "failed": failed, "fail_count": fail_count, "observed_count": observed_count}
            if isinstance(item, dict):
                item_fail_count = coerce_nonnegative_int(item.get("fail_count"))
                item_failed_runs = coerce_nonnegative_int(item.get("failed_runs"))
                item_observed_count = coerce_nonnegative_int(item.get("observed_count"))
                item_total_runs = coerce_nonnegative_int(item.get("total_runs"))
                if item_fail_count is not None:
                    record["fail_count"] = item_fail_count
                elif item_failed_runs is not None:
                    record["fail_count"] = item_failed_runs
                if item_observed_count is not None:
                    record["observed_count"] = max(1, item_observed_count)
                if item_total_runs is not None:
                    record["observed_count"] = max(1, item_total_runs)
            records.append(record)
        if records:
            return records

    return records


def merge_context(parent: dict[str, Any], child: dict[str, Any]) -> dict[str, Any]:
    merged = dict(parent)
    for key in ("scenario", "instance", "sdk", "language", "lang", "benchmark", "model"):
        value = child.get(key)
        if value not in (None, ""):
            merged[key] = value
    return merged


def looks_like_run(mapping: dict[str, Any]) -> bool:
    if extract_tests_from_mapping(mapping):
        return True
    if any(key in mapping for key in ("failing_tests", "failed_tests", "failures")):
        return True
    summary = mapping.get("summary")
    if isinstance(summary, dict) and extract_numeric_pass_rate(mapping) is not None:
        return True
    return any(isinstance(mapping.get(key), (int, float)) for key in ("pass_rate", "average_pass_rate", "avg_pass_rate"))


def normalize_run(mapping: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    run_context = merge_context(context, mapping)
    scenario = str(run_context.get("scenario") or run_context.get("instance") or run_context.get("benchmark") or "unknown")
    sdk = str(run_context.get("sdk") or run_context.get("language") or run_context.get("lang") or "unknown")
    tests = extract_tests_from_mapping(mapping)
    pass_rate = extract_numeric_pass_rate(mapping)
    total_runs = coerce_nonnegative_int(mapping.get("total_runs")) or 1
    failed_runs = coerce_nonnegative_int(mapping.get("failed_runs"))
    return {
        "scenario": scenario,
        "sdk": sdk,
        "tests": tests,
        "pass_rate": pass_rate,
        "total_runs": total_runs,
        "failed_runs": failed_runs,
    }


def collect_runs(payload: Any, context: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    context = context or {}
    runs: list[dict[str, Any]] = []

    if isinstance(payload, list):
        for item in payload:
            runs.extend(collect_runs(item, context))
        return runs

    if not isinstance(payload, dict):
        return runs

    current_context = merge_context(context, payload)

    for key in ("runs", "attempts", "executions"):
        nested = payload.get(key)
        if isinstance(nested, list):
            for item in nested:
                runs.extend(collect_runs(item, current_context))

    results_value = payload.get("results")
    if isinstance(results_value, list):
        for item in results_value:
            runs.extend(collect_runs(item, current_context))
    elif isinstance(results_value, dict) and any(
        isinstance(results_value.get(key), list) for key in ("runs", "attempts", "executions")
    ):
        runs.extend(collect_runs(results_value, current_context))

    instances_value = payload.get("instances")
    if isinstance(instances_value, list):
        for item in instances_value:
            runs.extend(collect_runs(item, current_context))

    if looks_like_run(payload):
        runs.append(normalize_run(payload, current_context))

    unique_runs: list[dict[str, Any]] = []
    seen: set[tuple[Any, ...]] = set()
    for run in runs:
        fingerprint = (
            run["scenario"],
            run["sdk"],
            tuple(sorted((t["name"], int(t.get("fail_count", 0)), int(t.get("observed_count", 1))) for t in run["tests"])),
            str(run["pass_rate"]),
            int(run.get("total_runs", 1)),
            str(run.get("failed_runs")),
        )
        if fingerprint not in seen:
            seen.add(fingerprint)
            unique_runs.append(run)
    return unique_runs


def analyze_runs(runs: list[dict[str, Any]], fallback_pass_rate: float | None) -> dict[str, Any]:
    total_runs = 0
    pass_rates: list[float] = []
    group_stats: dict[tuple[str, str], dict[str, Any]] = {}
    rule_stats: dict[str, dict[str, Any]] = defaultdict(lambda: {
        "fail_count": 0,
        "observed_count": 0,
        "tests": set(),
    })
    unmapped_failures: set[str] = set()

    for run in runs:
        run_total = int(run.get("total_runs", 1))
        run_failed_runs = run.get("failed_runs")
        total_runs += run_total
        if isinstance(run.get("pass_rate"), (int, float)):
            pass_rates.append(float(run["pass_rate"]))

        scenario = run["scenario"]
        sdk = run["sdk"]
        key = (scenario, sdk)
        bucket = group_stats.setdefault(
            key,
            {
                "scenario": scenario,
                "sdk": sdk,
                "runs": 0,
                "failed_runs": 0,
                "pass_rates": [],
                "tests": set(),
                "rules": set(),
            },
        )
        bucket["runs"] += run_total
        if isinstance(run.get("pass_rate"), (int, float)):
            bucket["pass_rates"].append(float(run["pass_rate"]))

        run_has_mapped_failure = False
        seen_tests_in_run: set[str] = set()
        seen_rule_failures_in_run: set[str] = set()

        for test in run.get("tests", []):
            test_name = extract_test_name(test)
            canonical_test = mapped_test_name(test_name)
            rule = test_to_rule(test_name)
            observed_count = int(test.get("observed_count", 1)) if isinstance(test, dict) else 1
            fail_count = int(test.get("fail_count", 1)) if isinstance(test, dict) else 1
            failed = bool(test.get("failed", False)) if isinstance(test, dict) else True

            if rule is None:
                if failed:
                    unmapped_failures.add(test_name)
                continue

            if canonical_test and canonical_test not in seen_tests_in_run:
                rule_stats[rule]["observed_count"] += observed_count
                seen_tests_in_run.add(canonical_test)

            if failed or fail_count > 0:
                run_has_mapped_failure = True
                bucket["tests"].add(canonical_test or test_name)
                bucket["rules"].add(rule)
                if rule not in seen_rule_failures_in_run:
                    rule_stats[rule]["fail_count"] += fail_count
                    seen_rule_failures_in_run.add(rule)
                rule_stats[rule]["tests"].add(canonical_test or test_name)

        if run_has_mapped_failure:
            bucket["failed_runs"] += int(run_failed_runs) if isinstance(run_failed_runs, int) else 1

    avg_pass_rate = statistics.mean(pass_rates) if pass_rates else fallback_pass_rate
    instance_rows = []
    for bucket in sorted(group_stats.values(), key=lambda item: (item["scenario"], item["sdk"])):
        if bucket["failed_runs"] == 0:
            continue
        instance_rows.append(
            {
                "scenario": bucket["scenario"],
                "sdk": bucket["sdk"],
                "failed_runs": bucket["failed_runs"],
                "total_runs": bucket["runs"],
                "avg_pass_rate": statistics.mean(bucket["pass_rates"]) if bucket["pass_rates"] else avg_pass_rate,
                "tests": sorted(bucket["tests"]),
                "rules": sorted(bucket["rules"]),
            }
        )

    rule_rows = []
    for rule, stats in sorted(rule_stats.items()):
        observed = max(stats["observed_count"], stats["fail_count"], 1)
        fail_count = stats["fail_count"]
        if fail_count <= 0:
            continue
        failure_rate = round(fail_count / observed * 100, 1)
        rule_rows.append(
            {
                "rule": rule,
                "fail_count": fail_count,
                "observed_count": observed,
                "failure_rate": failure_rate,
                "consistent": fail_count >= observed,
                "tests": sorted(stats["tests"]),
            }
        )

    consistent_rules = [row["rule"] for row in rule_rows if row["consistent"]]
    affected_rules = consistent_rules or [row["rule"] for row in rule_rows]

    return {
        "average_pass_rate": avg_pass_rate if avg_pass_rate is not None else 0.0,
        "total_runs": total_runs,
        "instance_rows": instance_rows,
        "rule_rows": rule_rows,
        "affected_rules": affected_rules,
        "consistent_rules": consistent_rules,
        "unmapped_failures": sorted(unmapped_failures),
    }


def analyze_payload(payload: Any) -> dict[str, Any]:
    if isinstance(payload, list):
        payload = {"failing_tests": payload}

    if isinstance(payload, dict) and any(key in payload for key in ("failing_tests", "failed_tests")):
        wrapper = {
            "scenario": payload.get("scenario", "unknown"),
            "sdk": payload.get("sdk") or payload.get("language") or "unknown",
            "failing_tests": payload.get("failing_tests") or payload.get("failed_tests"),
            "summary": payload.get("summary", {}),
            "pass_rate": payload.get("pass_rate"),
            "total_runs": payload.get("total_runs"),
            "failed_runs": payload.get("failed_runs"),
        }
        runs = [normalize_run(wrapper, wrapper)]
    else:
        runs = collect_runs(payload)
        if not runs and isinstance(payload, dict):
            aggregate = payload.get("aggregate")
            if isinstance(aggregate, dict) and isinstance(aggregate.get("test_consistency"), dict):
                synthetic = {
                    "scenario": payload.get("scenario", payload.get("benchmark", "unknown")),
                    "sdk": payload.get("sdk") or payload.get("language") or "unknown",
                    "test_consistency": aggregate["test_consistency"],
                    "pass_rate": aggregate.get("pass_rate", {}).get("mean"),
                }
                runs = [normalize_run(synthetic, synthetic)]

    return analyze_runs(runs, extract_numeric_pass_rate(payload))


def build_issue_title(affected_rules: list[str], average_pass_rate: float) -> str:
    return (
        f"Skill-Efficacy Eval: {len(affected_rules)} SDK rules need improvement "
        f"(avg {format_percent(average_pass_rate)}% pass rate)"
    )


def render_issue_body(analysis: dict[str, Any], analysis_url: str, rules_dir: Path) -> str:
    lines = [
        "## Summary",
        "",
        f"- **Average pass rate**: {format_percent(analysis['average_pass_rate'])}%",
        f"- **Runs analyzed**: {analysis['total_runs']}",
        f"- **Mapped SDK rules affected**: {len(analysis['affected_rules'])}",
        f"- **Consistently failing mapped rules**: {len(analysis['consistent_rules'])}",
        "",
        "## Failing instances (scenario × SDK)",
        "",
        "| Scenario | SDK | Failed Runs | Total Runs | Avg Pass Rate | Failing Tests | Rules |",
        "|----------|-----|-------------|------------|---------------|---------------|-------|",
    ]

    if analysis["instance_rows"]:
        for row in analysis["instance_rows"]:
            tests = "<br>".join(f"`{name}`" for name in row["tests"]) or "n/a"
            rules = "<br>".join(f"`{rule}`" for rule in row["rules"]) or "n/a"
            lines.append(
                f"| {row['scenario']} | {row['sdk']} | {row['failed_runs']} | {row['total_runs']} | "
                f"{format_percent(row['avg_pass_rate'])}% | {tests} | {rules} |"
            )
    else:
        lines.append("| n/a | n/a | 0 | 0 | n/a | n/a | n/a |")

    lines.extend(
        [
            "",
            "## Per-rule failure frequency across all runs",
            "",
            "| Rule | Failed Runs | Observed Runs | Failure Rate | Consistency | Tests |",
            "|------|-------------|---------------|--------------|-------------|-------|",
        ]
    )

    if analysis["rule_rows"]:
        for row in analysis["rule_rows"]:
            consistency = "consistent" if row["consistent"] else "intermittent"
            tests = "<br>".join(f"`{name}`" for name in row["tests"]) or "n/a"
            lines.append(
                f"| `{row['rule']}` | {row['fail_count']} | {row['observed_count']} | "
                f"{format_percent(row['failure_rate'])}% | {consistency} | {tests} |"
            )
    else:
        lines.append("| n/a | 0 | 0 | 0% | n/a | n/a |")

    lines.extend(["", "## Suggested actions", ""])
    action_rules = analysis["affected_rules"] or [row["rule"] for row in analysis["rule_rows"]]
    if action_rules:
        for rule in action_rules:
            lines.append(
                f"- Update `{rules_dir.as_posix()}/{rule}.md` to provide clearer guidance."
            )
    else:
        lines.append("- Review the unmapped failures below and decide whether a new sdk-* rule is needed.")

    if analysis["unmapped_failures"]:
        lines.extend(["", "## Unmapped failing tests", ""])
        for test_name in analysis["unmapped_failures"]:
            lines.append(f"- `{test_name}`")

    lines.extend(
        [
            "",
            "## Skill-efficacy run analysis",
            "",
            f"- {analysis_url}",
        ]
    )
    return "\n".join(lines)


def create_issue(repo: str, title: str, body: str) -> None:
    command = [
        "gh",
        "issue",
        "create",
        "--repo",
        repo,
        "--title",
        title,
        "--body-file",
        "-",
    ]
    # Attempt with labels first; retry without if labels don't exist in the repo.
    label_args = ["--label", "msbench-eval", "--label", "skills-gap"]
    completed = subprocess.run(
        command + label_args,
        text=True,
        capture_output=True,
        input=body,
    )
    if completed.returncode != 0 and "label" in completed.stderr.lower():
        # Labels don't exist — create issue without them.
        completed = subprocess.run(
            command,
            check=True,
            text=True,
            capture_output=True,
            input=body,
        )
    elif completed.returncode != 0:
        print(completed.stderr, file=sys.stderr)
        raise SystemExit(completed.returncode)
    stdout = completed.stdout.strip()
    if stdout:
        print(stdout)


def main() -> int:
    args = parse_args()
    payload = load_input(args)
    analysis = analyze_payload(payload)
    rules_dir = detect_rules_dir()
    title = build_issue_title(analysis["affected_rules"], analysis["average_pass_rate"])
    body = render_issue_body(analysis, find_analysis_url(payload), rules_dir)

    if args.dry_run:
        print(f"Title: {title}\n")
        print(body)
        return 0

    try:
        create_issue(args.repo, title, body)
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.stderr or str(exc))
        return exc.returncode or 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
